EmployeeInformationSystem.WebUI/Controllers/LeaveController.cs
using EmployeeInformationSystem.Core.Contracts;
using EmployeeInformationSystem.Core.Models;
using EmployeeInformationSystem.Core.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace EmployeeInformationSystem.WebUI.Controllers
{
    [Authorize(Roles = "Manage Leave")]
    public class LeaveController : BaseController
    {

        IRepository<EmployeeDetail> EmployeeDetailContext;
        IRepository<Discipline> DisciplineContext;
        IRepository<Designation> DesignationContext;
        IRepository<DependentDetail> DependentDetailContext;
        IRepository<Level> LevelContext;
        IRepository<Degree> DegreeContext;
        IRepository<HoD> HoDContext;
        IRepository<Organisation> OrganisationContext;
        IRepository<PastExperience> PastExperienceContext;
        IRepository<PayScale> PayScaleContext;
        IRepository<PostingDetail> PostingDetailContext;
        IRepository<PromotionDetail> PromotionDetailContext;
        IRepository<Department> DepartmentContext;
        IRepository<QualificationDetail> QualificationDetailContext;
        IRepository<TelephoneExtension> TelephoneExtensionContext;
        IRepository<EmployeeAsHoD> EmployeeAsHoDDetailContext;
        IRepository<LeaveType> LeaveTypeContext;
        IRepository<LeaveMaster> LeaveMasterContext;
        IRepository<EmployeeLeaveDetails> EmployeeLeaveDetailsContext;
        IRepository<EmployeeLeaveBalance> EmployeeLeaveBalanceContext;

        public LeaveController(IRepository<EmployeeDetail> employeeDetailContext,
        IRepository<Discipline> disciplineContext,
        IRepository<DependentDetail> dependentDetailContext,
        IRepository<Level> levelContext,
        IRepository<Degree> degreeContext,
        IRepository<Designation> designationContext,
        IRepository<HoD> hoDContext,
        IRepository<Organisation> organisationContext,
        IRepository<PastExperience> pastExperienceContext,
        IRepository<PayScale> payScaleContext,
        IRepository<PostingDetail> postingDetailContext,
        IRepository<PromotionDetail> promotionDetailContext,
        IRepository<Department> departmentContext,
        IRepository<QualificationDetail> qualificationDetailContext,
        IRepository<TelephoneExtension> telephoneExtensionContext,
        IRepository<EmployeeAsHoD> employeeAsHoDDetailContext,
        IRepository<LeaveType> leaveTypeContext,
        IRepository<LeaveMaster> leaveMasterContext,
        IRepository<EmployeeLeaveDetails> employeeLeaveDetailsContext,
        IRepository<EmployeeLeaveBalance> employeeLeaveBalanceContext
        )
        {
            EmployeeDetailContext = employeeDetailContext;
            DisciplineContext = disciplineContext;
            LevelContext = levelContext;
            DegreeContext = degreeContext;
            DependentDetailContext = dependentDetailContext;
            DesignationContext = designationContext;
            HoDContext = hoDContext;
            OrganisationContext = organisationContext;
            PastExperienceContext = pastExperienceContext;
            PostingDetailContext = postingDetailContext;
            PayScaleContext = payScaleContext;
            PromotionDetailContext = promotionDetailContext;
            DepartmentContext = departmentContext;
            QualificationDetailContext = qualificationDetailContext;
            TelephoneExtensionContext = telephoneExtensionContext;
            EmployeeAsHoDDetailContext = employeeAsHoDDetailContext;
            LeaveTypeContext = leaveTypeContext;
            LeaveMasterContext = leaveMasterContext;
            EmployeeLeaveDetailsContext = employeeLeaveDetailsContext;
            EmployeeLeaveBalanceContext = employeeLeaveBalanceContext;
            //Setting Parameters for Page

            base.SetGlobalParameters();
            ViewBag.UserName = UserName;
            ViewBag.ProfilePhoto = ProfilePicture;
            ViewBag.Role = Role;
        }

        // GET: Leave
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LeaveMaster()
        {


            List<Organisation> orgList = OrganisationContext.Collection().OrderBy(e => e.Name).ToList();
            ViewBag.OrganisationList = orgList;

            List<LeaveType> LeaveType = LeaveTypeContext.Collection().OrderBy(e => e.Name).ToList();
            ViewBag.LevelTypeList = LeaveType;


            ViewBag.targetmodel = "LeaveMaster";
            ViewBag.HeadingName = "Add Leave Quota";
            ViewBag.HeadingColor = "bg-success";

            return View();
        }

        public ActionResult ViewLeaveQuota()
        {
            DataTable dt_ = null;
            var LQ_data = (from leaveMaster in LeaveMasterContext.Collection().ToList()

                           join orgC in OrganisationContext.Collection().ToList()
                           on leaveMaster.OrganisationId equals orgC.Id

                           join lt in LeaveTypeContext.Collection().ToList()
                           on leaveMaster.LeaveTypeId equals lt.Id

                           select new
                           {
                               Organisation = orgC.Name,
                               LeaveType = lt.Name,
                               leaveMaster.AnnualQuota,
                               leaveMaster.ValidFrom,
                               leaveMaster.ValidTill,
                               leaveMaster.Id


                           }

                       ).OrderBy(x => x.Organisation).ToList();

            dt_ = ToDataTable(LQ_data);
            ViewBag.targetmodel = "LeaveMaster";
            ViewBag.HeadingName = "View Leave Quota";
            ViewBag.HeadingColor = "bg-info";
            return View("ShowResponse", dt_);
        }

        public ActionResult Edit(string idData, string targetmodel)
        {


            var viewname = "";
            switch (targetmodel)
            {
                case "LeaveType":
                    LeaveType lt = new LeaveType();
                    var LT_data = LeaveTypeContext.Collection().Where(a => a.Id == idData).ToList();
                    foreach (var item in LT_data)
                    {
                        lt.Name = item.Name;
                        lt.Id = item.Id;
                    }
                    viewname = "LeaveType";
                    ViewBag.Name = viewname;
                    ViewBag.HeadingName = "Update Leave Type";
                    ViewBag.HeadingColor = "bg-warning ";
                    return View(viewname, lt);

                case "LeaveMaster":

                    LeaveMaster lm = new LeaveMaster();
                    var LQ_data = (from leaveMaster in LeaveMasterContext.Collection().ToList()

                                   join orgC in OrganisationContext.Collection().ToList()
                                   on leaveMaster.OrganisationId equals orgC.Id

                                   join ltC in LeaveTypeContext.Collection().ToList()
                                   on leaveMaster.LeaveTypeId equals ltC.Id

                                   select new
                                   {
                                       Organisation = orgC.Name,
                                       LeaveType = ltC.Name,
                                       leaveMaster.AnnualQuota,
                                       leaveMaster.ValidFrom,
                                       leaveMaster.ValidTill,
                                       leaveMaster.Id


                                   }

                        ).Where(x => x.Id == idData).ToList();

                    foreach (var item in LQ_data)
                    {
                        lm.AnnualQuota = item.AnnualQuota;
                        lm.ValidFrom = item.ValidFrom;
                        lm.ValidTill = item.ValidTill;
                        ViewBag.LName = item.LeaveType;
                        ViewBag.OName = item.Organisation;
                        lm.Id = item.Id;

                    }

                    ViewBag.Action = "UpdateLeaveMaster";
                    List<Organisation> orgList = OrganisationContext.Collection().OrderBy(e => e.Name).ToList();
                    ViewBag.OrganisationList = orgList;

                    List<LeaveType> LeaveType = LeaveTypeContext.Collection().OrderBy(e => e.Name).ToList();
                    ViewBag.LevelTypeList = LeaveType;

                    viewname = "LeaveMaster";
                    return View(viewname, lm);
                    //break;

            }
            return View(viewname);
        }

        public ActionResult Delete(string idData, string targetmodel)
        {
            var viewname = "";
            switch (targetmodel)
            {
                case "LeaveType":
                    LeaveType lt = new LeaveType();
                    var LT_data = LeaveTypeContext.Collection().Where(a => a.Id == idData).ToList();
                    foreach (var item in LT_data)
                    {
                        lt.Name = item.Name;
                        lt.Id = item.Id;
                    }
                    viewname = "LeaveType";
                    ViewBag.Name = "DeleteLeaveType";
                    ViewBag.HeadingName = "Delete Leave Type";
                    ViewBag.HeadingColor = "bg-danger";
                    return View(viewname, lt);
                //break;


                case "LeaveMaster":

                    LeaveMaster lm = new LeaveMaster();
                    var LQ_data = (from leaveMaster in LeaveMasterContext.Collection().ToList()

                                   join orgC in OrganisationContext.Collection().ToList()
                                   on leaveMaster.OrganisationId equals orgC.Id

EmployeeInformationSystem.WebUI/Views/Leave/AddLeavesDue.cshtml
@model EmployeeInformationSystem.Core.Models.EmployeeLeaveBalance
@{
    ViewBag.Title = "AddLeavesDue";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/bootstrap-select")
@Styles.Render("~/Content/gijgo")
<header class="page-header @ViewBag.HeadingColor  text-white">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">@ViewBag.HeadingName </h2>
    </div>
</header>
<section class="forms">
    @if (ViewBag.Msg == null)
    {
        <div class="container-fluid" style="position:relative">
            <div class="container-fluid">
                <div class="row" id="reportDisplayBlock">
                    <div class="col-lg-12">
                        <div class="card">
                            @using (Html.BeginForm("AddLeavesDue", "Leave", FormMethod.Post, new { @class = "form-horizontal", @data_heading = "Add Leave Type" }))
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="card-body">
                                    <div class="form-group row">
                                        <label class="form-control-label col-sm-3 d-flex justify-content-center">Employee Name</label>
                                        <div class="col-sm-4">
                                            <select name="EmployeeId" class="form-control select" id="selectEmployeeByName" style="min-width:80%;" data-live-search="true">
                                                <option value="0" selected>--Select Employee--</option>
                                                @foreach (var emp in ViewBag.EmlployeeTypeList)
                                                {
                                                    <option value="@emp.Id" data-employeetype="@emp.FirstName">@emp.FirstName @emp.MiddleName @emp.LastName</option>
                                                }
                                            </select>
                                        </div>
                                        <div class="col-sm-4">
                                            <div classs="col-sm-9 align-left" style="display:none;color: red;" id="errorEmployeeId">Please Select Employee Name</div>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="form-control-label col-sm-3 d-flex justify-content-center">Leave Type</label>
                                        <div class="col-sm-4">
                                            <select name="LeaveTypeId" class="form-control" id="selectLeaveTypeName" style="min-width:80%;" data-live-search="true">
                                                <option value="0" selected>--Select Leave Type--</option>
                                               @*@foreach (var leave in ViewBag.TypeList)
                                                {
                                                    <option value="@leave.Id" data-employeetype="@leave.Name">@leave.Name</option>
                                                }*@
                                            </select>
                                        </div>
                                        <div class="col-sm-4">
                                            <div classs="col-sm-9 align-left" style="display:none;color: red;" id="errorLeaveId">Please Select Leave Type</div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="form-control-label col-sm-3 d-flex justify-content-center">No of Leaves</label>
                                        <div class="col-sm-4">
                                            @Html.EditorFor(model => model.AvailableLeaveCount, new { htmlAttributes = new { @class = "form-control", @type = "number", @data_type = "number", autocomplete = "off" } })

                                        </div>
                                        <div class="col-sm-4">
                                            <div classs="col-sm-9 align-left" style="display:none;color: red;" id="errorNoOfDays">Please Enter No of Leaves</div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-9 offset-sm-4">
                                            <input type="submit" value="Apply" class="btn btn-primary" id="ApplyLeaveBtn">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-sm-8" id="tblCard" style="display:none">
                                            <table class="table table-striped table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th>Leave Type</th>
                                                        <th>No. of Leaves Due</th>
                                                    </tr>
                                                </thead>
                                                <tbody id="TblLeaveData"></tbody>
                                            </table>
                                            </div>
                                    </div>                          
                        </div>
                            }
                    </div>
                </div>
            </div>
        </div>
        </div>
    }
    else
    {
        <div class="container-fluid" style="position:relative">
            <div class="container-fluid">
                <div class="row" id="reportDisplayBlock">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body" id="reportDisplayBody">
                                <p>@ViewBag.Msg</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>
@section Scripts{
    @Scripts.Render("~/bundles/bootstrap-select")
    @Scripts.Render("~/bundles/gijgo")
<script>
                            $(document).ready(function () {


                                $(document).on('change', '#selectEmployeeByName', function () {
                                  //  var empid = $(this).children(":selected").val();
                                    ////alert(empid);
                                     var data = {
                                         'EmployeeId': $("#selectEmployeeByName option:selected").val()    
                                                }              

                                    postData("Leave/Get_Leave_Employee ", data, "Leavedata", "Leave");
                                });

        $(document).on('click', '#ApplyLeaveBtn', function (e) {
           var isValid = true;
           var australianDate = /^(?=\d)(?:(?:31(?!.(?:0?[2469]|11))|(?:30|29)(?!.0?2)|29(?=.0?2.(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00)))(?:\x20|$))|(?:2[0-8]|1\d|0?[1-9]))([-./])(?:1[012]|0?[1-9])\1(?:1[6-9]|[2-9]\d)?\d\d(?:(?=\x20\d)\x20|$))?(((0?[1-9]|1[012])(:[0-5]\d){0,2}(\x20[AP]M))|([01]\d|2[0-3])(:[0-5]\d){1,2})?$|^$/;

            if ($("#selectEmployeeByName").val() == 0) {
                $("#errorEmployeeId").show();
                isValid = false;
            } else {
                $("#errorEmployeeId").hide();
            }


            if ($("#selectLeaveTypeName").val() == 0) {
                $("#errorLeaveId").show(); isValid = false;
            } else {
                $("#errorLeaveId").hide();
            }


            if ($("#@Html.IdFor(model => model.AvailableLeaveCount)").val() == "") {
                $("#errorNoOfDays").show(); isValid = false;
            }
            else { $("#errorNoOfDays").hide(); }



            if (!isValid) {
                e.preventDefault(); //prevent the default action
            } else {
                $('#overlay').fadeIn(); // show spinner
            }
            });

        });

</script>
    <script>

        var getUrl = window.location
        var aURL = getUrl.protocol + "//" + getUrl.host + "/" + getUrl.pathname.split('/')[1] + "/";


        function postData(api, inputData, aBy, aTyp) {
            $.ajax({
                type: "POST",
                url: aURL + api,
                data: JSON.stringify(inputData),
                dataType: "JSON",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    PostDone(data, aBy, aTyp);
                },
                error: function (err) {
                    window.location.href = aURL;
                    //alert("Something went wrong");
                }
            });
        }


        PostDone = function (data, aBy, aTyp) {

            if (aTyp === "Leave") {
                if (aBy === "Leavedata") {
                    if (data.length > 0) {
                        $('#TblLeaveData').empty();
                        $('#tblCard').css('display', 'block');
                        $.each(data, function (Key, value) {
                            $('#TblLeaveData').append('<tr role="row"><td class="tableRow">' + value.LeaveType + '</td><td>' + value.LeaveCount + '</td></tr>');

                        });

                        var data = {
                            'EmployeeId': $("#selectEmployeeByName option:selected").val()
                        }
                        postData("Leave/Get_Leave_List_Employee ", data, "dropdown", "LeaveOrgReport");

                    }
                    else {
                        $('#TblLeaveData').empty();
                        $('#tblCard').css('display', 'block');
                        $('#TblLeaveData').append('<tr role="row"><td colspan="2" style="text-align:center"> No records found </td></tr>');


                    }
                    $('#overlay').fadeOut();
                }
            }
            if (aTyp === "LeaveOrgReport") {
                document.getElementById("selectLeaveTypeName").innerHTML = null;
                    if (aBy === "dropdown") {
                        var Items = "<option value=0>--Select Leave Type--</option>";
                        $('#selectLeaveTypeName').append(Items);
                        if (data) {                        
                       
                        $.each(data, function (Key, value) {
                            $('#selectLeaveTypeName').append(
                                $('<option></option>').val(value.LeaveTypeId).text(value.Name));
                        });
                    }
                }
            }
        }




    </script>
}

EmployeeInformationSystem.WebUI/Views/Leave/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model EmployeeInformationSystem.Core.Models.LeaveMaster

@{
    ViewBag.Title = "LeaveMaster";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/bootstrap-select")
@Styles.Render("~/Content/gijgo")


@if (ViewBag.Msg == null)
{


    <div class="container-fluid" style="position:relative">
        <div class="container-fluid">
            <div class="row" id="reportDisplayBlock">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center">
                            Leave Quota
                        </div>




                        @using (Html.BeginForm("AddLeaveQuota", "Leave", FormMethod.Post, new { @class = "form-horizontal", @id = "customReportSelectionForm", @data_heading = "Add Leave Quota" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                            <div class="card-body" id="reportDisplayBody">


                                <div class="form-group row">
                                    <label class="col-sm-3 form-control-label">Organisation</label>
                                    <div class="col-sm-5">
                                        <select name="OrganisationId" class="form-control selectEmployeeOption" id="selectEmployeeByName" style="min-width:80%;" data-live-search="true">
                                            <option value="0" selected>--Select Organisation--</option>
                                            @foreach (var employee in ViewBag.OrganisationList)
                                            {
                                                <option value="@employee.Id" data-employeetype="@employee.Name">@employee.Name</option>
                                            }
                                        </select>
                                    </div>

                                </div>
                                <div class="form-group row offset-sm-3">
                                    <div classs="col-sm-9" style="display:none;color: red;" id="errorOrg">Please select columns</div>
                                </div>


                                <div class="form-group row">
                                    <label class="col-sm-3 form-control-label">Leave Type</label>
                                    <div class="col-sm-5">
                                        <select name="LeaveTypeId" class="form-control selectEmployeeOption" id="selectEmployeeByName" style="min-width:80%;" data-live-search="true">
                                            <option value="0" selected>--Select Leave Type--</option>
                                            @foreach (var employee in ViewBag.LevelTypeList)
                                            {
                                                <option value="@employee.Id" data-employeetype="@employee.Name">@employee.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row offset-sm-3">
                                    <div classs="col-sm-9" style="display:none;color: red;" id="errorLeave">Please select columns</div>
                                </div>


                                <div class="form-group row">
                                    @Html.LabelFor(model => model.AnnualQuota, htmlAttributes: new { @class = "col-sm-3 form-control-label" })
                                    <div class="col-sm-5">
                                        @Html.EditorFor(model => model.AnnualQuota, new { htmlAttributes = new { @class = "form-control", @type = "text", @data_type = "text" } })
                                    </div>
                                    <div classs="col-sm-4" style="display:none;color: red;" id="errorAQ">Please enter annual quota</div>
                                </div>

                                <div class="form-group row">
                                    @Html.LabelFor(model => model.ValidFrom, htmlAttributes: new { @class = "col-sm-3 form-control-label" })
                                    <div class="col-sm-5">
                                        @Html.EditorFor(model => model.ValidFrom, new { htmlAttributes = new { @class = "form-control", @type = "text", @data_type = "date", autocomplete = "off" } })
                                    </div>
                                    <div classs="col-sm-4" style="display:none;color: red;" id="errorFromDate">Please input valid date</div>
                                </div>

                                <div class="form-group row">
                                    @Html.LabelFor(model => model.ValidTill, htmlAttributes: new { @class = "col-sm-3 form-control-label" })
                                    <div class="col-sm-5">
                                        @Html.EditorFor(model => model.ValidTill, new { htmlAttributes = new { @class = "form-control", @type = "text", @data_type = "date", autocomplete = "off" } })
                                    </div>
                                    <div classs="col-sm-4" style="display:none;color: red;" id="errorToDate">Please input valid date</div>
                                </div>






                                <div class="form-group row">
                                    <div class="col-sm-9 offset-sm-3">
                                        <input type="submit" value="Add" class="btn btn-primary" id="reportSubmitBtn">
                                    </div>
                                </div>

                            </div>

                        }


                    </div>
                </div>

            </div>
        </div>

    </div>}
else
{

    <div class="container-fluid" style="position:relative">
        <div class="container-fluid">
            <div class="row" id="reportDisplayBlock">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center">
                            Leave Quota
                        </div>

                        <div class="card-body" id="reportDisplayBody">

                            <p>@ViewBag.Msg</p>

                        </div>


                    </div>
                </div>

            </div>
        </div>

    </div>
}

@section Scripts{
    @Scripts.Render("~/bundles/bootstrap-select")
    @Scripts.Render("~/bundles/gijgo")
    <script>
    $(document).ready(function () {

        $('select').selectpicker();
                            $('[data-type="date"]').each(function () {
                                $(this).datepicker({
                                    uiLibrary: 'bootstrap',
                                    format: 'dd-mm-yyyy'
                                });
                            });
        $(document).on('click', '#reportSubmitBtn', function (e) {
           var isValid = true;
           var australianDate = /^(?=\d)(?:(?:31(?!.(?:0?[2469]|11))|(?:30|29)(?!.0?2)|29(?=.0?2.(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00)))(?:\x20|$))|(?:2[0-8]|1\d|0?[1-9]))([-./])(?:1[012]|0?[1-9])\1(?:1[6-9]|[2-9]\d)?\d\d(?:(?=\x20\d)\x20|$))?(((0?[1-9]|1[012])(:[0-5]\d){0,2}(\x20[AP]M))|([01]\d|2[0-3])(:[0-5]\d){1,2})?$|^$/;

            if ($("#@Html.IdFor(model => model.OrganisationId) option:selected").val()== 0) {
               $("#errorOrg").show(); isValid = false;
           } else {
                $("#errorOrg").hide();
           }

          if ($("#@Html.IdFor(model => model.LeaveTypeId) option:selected").val()== 0) {
               $("#errorLeave").show(); isValid = false;
           } else {
                $("#errorLeave").hide();
            }

            var asdhfashd = $("#OrganisationId option:selected").text();
            if ($("#OrganisationId option:selected").val() == 0) {
                $("#errorLeave").show(); isValid = false;
            }
            else {
                 $("#errorLeave").hide();
            }

            if ($("#@Html.IdFor(model => model.AnnualQuota)").val() == "") {
                $("#errorAQ").show(); isValid = false;
            } else {
                $("#errorAQ").hide();
            }

           if (!australianDate.test($("#@Html.IdFor(model => model.ValidFrom)").val())) {
               $("#errorFromDate").show(); isValid = false;
               console.log($("#@Html.IdFor(model => model.ValidFrom)").val());
           } else {
               $("#errorFromDate").hide();
           }

           if (!australianDate.test($("#@Html.IdFor(model => model.ValidTill)").val())) {
               console.log($("#@Html.IdFor(model => model.ValidTill)").val());
               $("#errorToDate").show(); isValid = false;
           } else {
                $("#errorToDate").hide();
           }



            if (!isValid) {
                e.preventDefault(); //prevent the default action
            } else {
                $('#overlay').fadeIn(); // show spinner
            }
           });
        });
    </script>

}

EmployeeInformationSystem.WebUI/Views/Leave/ErrorPage.cshtml
@{
    ViewBag.Title = "Error Page";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/bootstrap-select")
@Styles.Render("~/Content/gijgo")
<header class="page-header bg-danger  text-white">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Error</h2>
    </div>
</header>