EmployeeInformationSystem.WebUI/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace EmployeeInformationSystem.WebUI.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }

    public class ModifyAccountViewModel
    {
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New Password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }

        //Custom Fields
        public string Id { get; set; }

        [Required(ErrorMessage = "Valid User ID is required")]
        [Display(Name = "User ID")]
        public string UserId { get; set; }

        [Display(Name = "Employee Name")]
        public string EmployeeName { get; set; }

        // Managing Roles & Claims
        public bool Admin { get; set; }
        public bool AddEmployee { get; set; }
        public bool ViewEmployee { get; set; }
        public bool EditEmployee { get; set; }
        public bool DeleteEmployee { get; set; }
        public bool GenerateReports { get; set; }
        public bool ManageLeave { get; set; }
    }

    public class MissingData
    {
        public string Title { get; set; }
        public int CountValue { get; set; }
    }

   
}

EmployeeInformationSystem.WebUI/Controllers/MasterDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExcelDataReader;
using System.Data;
using System.IO;
using EmployeeInformationSystem.Core.Contracts;
using EmployeeInformationSystem.Core.Models;
using System.Text.RegularExpressions;
using EmployeeInformationSystem.Core.ViewModels;
using System.Net;

namespace EmployeeInformationSystem.WebUI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MasterDataController : BaseController
    {
        IRepository<EmployeeDetail> EmployeeDetailContext;
        IRepository<Discipline> DisciplineContext;
        IRepository<Designation> DesignationContext;
        IRepository<DependentDetail> DependentDetailContext;
        IRepository<Level> LevelContext;
        IRepository<Degree> DegreeContext;
        IRepository<HoD> HoDContext;
        IRepository<Organisation> OrganisationContext;
        IRepository<PastExperience> PastExperienceContext;
        IRepository<PayScale> PayScaleContext;
        IRepository<PostingDetail> PostingDetailContext;
        IRepository<PromotionDetail> PromotionDetailContext;
        IRepository<Department> DepartmentContext;
        IRepository<QualificationDetail> QualificationDetailContext;
        IRepository<TelephoneExtension> TelephoneExtensionContext;
        // Logging.. 
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public MasterDataController(IRepository<EmployeeDetail> employeeDetailContext,
        IRepository<Discipline> disciplineContext,
        IRepository<DependentDetail> dependentDetailContext,
        IRepository<Level> levelContext,
        IRepository<Degree> degreeContext,
        IRepository<Designation> designationContext,
        IRepository<HoD> hoDContext,
        IRepository<Organisation> organisationContext,
        IRepository<PastExperience> pastExperienceContext,
        IRepository<PayScale> payScaleContext,
        IRepository<PostingDetail> postingDetailContext,
        IRepository<PromotionDetail> promotionDetailContext,
        IRepository<Department> departmentContext,
        IRepository<QualificationDetail> qualificationDetailContext,
        IRepository<TelephoneExtension> telephoneExtensionContext)
        {
            EmployeeDetailContext = employeeDetailContext;
            DisciplineContext = disciplineContext;
            LevelContext = levelContext;
            DegreeContext = degreeContext;
            DependentDetailContext = dependentDetailContext;
            DesignationContext = designationContext;
            HoDContext = hoDContext;
            OrganisationContext = organisationContext;
            PastExperienceContext = pastExperienceContext;
            PostingDetailContext = postingDetailContext;
            PayScaleContext = payScaleContext;
            PromotionDetailContext = promotionDetailContext;
            DepartmentContext = departmentContext;
            QualificationDetailContext = qualificationDetailContext;
            TelephoneExtensionContext = telephoneExtensionContext;

            //Setting Parameters for Page
            base.SetGlobalParameters();
            ViewBag.UserName = UserName;
            ViewBag.ProfilePhoto = ProfilePicture;
            ViewBag.Role = Role;

        }


        // GET: MasterData
        public ActionResult Index()
        {
            List<EmployeeDetail> employees = EmployeeDetailContext.Collection().OrderBy(e => e.FirstName).ToList();
            ViewBag.Employees = employees;
            return View();
        }

        [HttpPost]
        public ActionResult AjaxBulkUpload(HttpPostedFileBase file)
        {
            var returnText = " < div class=\"alert alert-danger\" role=\"alert\"> Nothing Recieved </div>";
            int inserted = 0, skipped = 0, failed = 0;
            if (null != file && 0 < file.ContentLength)
            {
                // ExcelDataReader works with the binary Excel file, so it needs a FileStream
                // to get started. This is how we avoid dependencies on ACE or Interop:
                Stream stream = file.InputStream;

                // We return the interface, so that
                IExcelDataReader reader = null;

                var extension = Path.GetExtension(file.FileName).ToLower();
                returnText = "Successfully Recieved correct file";

                if (".xls" == extension)
                {
                    reader = ExcelReaderFactory.CreateBinaryReader(stream);
                }
                else if (".xlsx" == extension)
                {
                    reader = ExcelReaderFactory.CreateOpenXmlReader(stream);
                }
                else
                {
                    returnText = "<div class=\"alert alert-danger\" role=\"alert\"> Wrong File Format uploaded!</div>";
                    return Content(returnText);
                }

                DataTable dt_ = new DataTable();
                dt_ = reader.AsDataSet().Tables[0];

                if ("Dep, Consultants, Associates" != dt_.TableName)
                {
                    returnText = "<div class=\"alert alert-danger\" role=\"alert\"> Wrong File Format uploaded! </div>";
                    return Content(returnText);
                }

                // Get Column names
                List<string> columnNames = new List<string>();

                for (int i = 0; i < dt_.Columns.Count; i++)
                {
                    log.Info("Sheet 1, Column no. " + i + ": " + dt_.Rows[0][i].ToString());
                    columnNames.Add(dt_.Rows[0][i].ToString());
                }
                for (int row_ = 1; row_ < dt_.Rows.Count; row_++)
                {
                    //Employee Code
                    string cpfNo = dt_.Rows[row_][columnNames.FindIndex(c => c == "CPF No.")].ToString();

                    EmployeeDetail employeeToInsert = EmployeeDetailContext.Collection().FirstOrDefault(e => e.EmployeeCode == cpfNo);
                    bool employeeInserted = false;

                    if (null != employeeToInsert)
                    {
                        log.Info("Employee with CPF:" + cpfNo + " already exists. Skipping Entry");
                        skipped++;
                    }
                    else
                    {

                        string DGHId = (from organisation in OrganisationContext.Collection()
                                        where organisation.Name == "DGH"
                                        select organisation.Id).FirstOrDefault();
                        if (string.IsNullOrEmpty(DGHId))
                        {
                            Organisation dghOrganisation = new Organisation() { Name = "DGH" };
                            OrganisationContext.Insert(dghOrganisation);
                            OrganisationContext.Commit();
                            DGHId = dghOrganisation.Id;
                            log.Info("Added Organisation : DGH");
                        }

                        //Organisation
                        string organisationName = dt_.Rows[row_][columnNames.FindIndex(c => c == "Parent Org.")].ToString();
                        string organisationId = (from organisation in OrganisationContext.Collection()
                                                 where organisation.Name == organisationName
                                                 select organisation.Id).FirstOrDefault();
                        if (null == organisationId && "Not Applicable" != organisationName)
                        {
                            Organisation newOrganisation = new Organisation() { Name = organisationName };
                            OrganisationContext.Insert(newOrganisation);
                            OrganisationContext.Commit();
                            organisationId = newOrganisation.Id;
                            log.Info("Added Organisation :" + organisationName);
                        }

                        // Discipline
                        string disciplineName = dt_.Rows[row_][columnNames.FindIndex(c => c == "Discipline Name")].ToString();
                        string disciplineId = (from discipline in DisciplineContext.Collection()
                                               where discipline.Name == disciplineName
                                               select discipline.Id).FirstOrDefault();
                        if (null == disciplineId && !string.IsNullOrEmpty(disciplineName))
                        {
                            Discipline newDiscipline = new Discipline() { Name = disciplineName };
                            DisciplineContext.Insert(newDiscipline);
                            DisciplineContext.Commit();
                            disciplineId = newDiscipline.Id;
                            log.Info("Added Discipline :" + disciplineName);
                        }

                        //Level
                        string dghLevelName = dt_.Rows[row_][columnNames.FindIndex(c => c == "DGH Level")].ToString();
                        string dghLevelId = (from level in LevelContext.Collection()
                                             where level.Name == dghLevelName
                                             select level.Id).FirstOrDefault();
                        if (null == dghLevelId && !string.IsNullOrEmpty(dghLevelName))
                        {
                            Level newLevel = new Level() { Name = dghLevelName, OrganisationId = DGHId };
                            LevelContext.Insert(newLevel);
                            LevelContext.Commit();
                            dghLevelId = newLevel.Id;
                            log.Info("Added Level :" + dghLevelName);
                        }

                        // Other Fields

                        //Employee Type

EmployeeInformationSystem.WebUI/Views/MasterData/Degree.cshtml
@model EmployeeInformationSystem.Core.ViewModels.DataViewModel
@{ViewBag.Title = "Master Data Management";}

@section CustomStyles{
    <style>
        #overlay {
            position: absolute;
            justify-content: left;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba(130, 130, 130, 0.5);
        }
    </style>

}
@section Admin{
    class="active"
}

<div id="overlay" style="display:none;text-align:center;">
    <img src="~/Content/img/spinner.gif" style="resize:inherit;" />
    <br />
</div>


<!-- Page Header-->
<header class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Manage - Degrees</h2>
    </div>
</header>
<!-- Forms Section-->
<section class="forms">
    <div class="container-fluid" style="position:relative">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center">
                            <h3 class="h4">Degree List</h3>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-primary ml-auto modalBtn" data-targetid="newDegree" data-role="Add">
                                Add New
                            </button>
                        </div>
                        <div class="card-body" style="overflow-y: scroll; max-height: 550px;">

                            <table class="table table-striped table-hover">
                                <tr>

                                    <th>
                                        @Html.DisplayNameFor(model => model.Degrees.First().Name)
                                    </th>
                                    <th>Action</th>
                                </tr>

                                @foreach (var item in Model.Degrees)
                                {
                                    <tr>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            <a href="#" class="modalBtn" data-targetid="@item.Id" data-role="Edit">Edit</a> |
                                            <a href="#" class="modalBtn" data-targetid="@item.Id" data-role="Delete">Delete</a>
                                        </td>
                                    </tr>
                                }

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalBody">
                    ...
                </div>
                <div class="modal-footer" id="modalFooter">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" id="closeBtn" data-pagerefresh="false">Close</button>
                    <button type="button" class="btn btn-primary" id="saveChangesBtn">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script>
        $(document).ready(function () {

            $('#modal').on('hidden.bs.modal', function () {
                if ("true" == $("#closeBtn").data("pagerefresh")) location.reload();
            });

            $(".modalBtn").click(function () {
                $('#overlay').fadeIn();
                var id = $(this).data("targetid");
                var role = $(this).data("role");
                if ("" != role) {

                    $.ajax({
                        url: '@Url.Action("ManageForm", "MasterData")?mode=' + role + '&dataType=Degree' + '&Id=' + id,
                        success: function (result) {
                            $("#modalBody").html(result);
                            $("#saveChangesBtn").show();
                        },
                        error: function () {
                            $('#modalBody').html('<div class="alert alert-danger" role="alert"> An Error has occured </div >');
                            $("#saveChangesBtn").hide();
                        },
                        fail: function (xhr, textStatus, errorThrown) {
                            $('#modalBody').html('<div class="alert alert-danger" role="alert">Request Failed with error: ' + errorThrown + '</div > ');
                            $("#saveChangesBtn").hide();
                        },
                        complete: function () {
                            $('#overlay').fadeOut();
                            $("#modalTitle").html(role +" Degree");
                            $('#modal').modal('show');
                        }
                    });
                }
            });

            $("#saveChangesBtn").click(function () {
                $('#overlay').fadeIn();
                var formType = $('#manageForm').data('formtype');
                var formUrl = $('#manageForm').attr('action') + "?mode=" + formType;
                var formData = new FormData(document.getElementById('manageForm'));
                var text = null;
                switch (formType) {
                    case "Add": text = "added"; break;
                    case "Edit": text = "updated"; break;
                    case "Delete": text = "deleted"; break;
                }
                $.ajax({
                    url: formUrl,
                    type: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (result) {
                        if ('Success' == result) {
                            $('#modalBody').html('<div class="alert alert-success" role="alert"> Successfully ' + text + ' degree</div >');
                            $("#saveChangesBtn").fadeOut();
                            $("#closeBtn").data("pagerefresh", "true")
                        } else {
                            $('#modalBody').html(result);
                            $("#saveChangesBtn").show();
                        }
                    },
                    error: function () {
                        $('#modalBody').html('<div class="alert alert-danger" role="alert"> An Error has occured </div >');
                        $("#saveChangesBtn").fadeOut();
                    },
                    fail: function (xhr, textStatus, errorThrown) {
                        $('#modalBody').html('<div class="alert alert-danger" role="alert">Request Failed with error: ' + errorThrown + '</div > ');
                        $("#saveChangesBtn").fadeOut();
                    },
                    complete: function () {
                        $('#overlay').fadeOut();
                    }
                });
            });

        });
    </script>
}

EmployeeInformationSystem.WebUI/Views/MasterData/DegreeForm.cshtml
@model EmployeeInformationSystem.Core.Models.Degree

@{
    Layout = null;
}


@using (Html.BeginForm("Degree", "MasterData", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "manageForm", @data_formtype = ViewBag.Mode }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id, new { Value = @Model.Id })

    if ("Delete" == ViewBag.Mode)
    {
        <div class="alert alert-warning" role="alert">
            Are you sure?
            This will delete this Degree and its dependent data!
        </div>

        <div class="form-group row">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-3 form-control-label" })
            <div class="col-9">
                @Html.HiddenFor(model => model.Name, new { Value = @Model.Name })
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    }

    else
    {

        <div class="form-group row">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-3 form-control-label" })
            <div class="col-9">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    }
}

EmployeeInformationSystem.WebUI/Views/MasterData/Department.cshtml
@model EmployeeInformationSystem.Core.ViewModels.DataViewModel
@{ViewBag.Title = "Master Data Management";}

@section CustomStyles{
    <style>
        #overlay {
            position: absolute;
            justify-content: left;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba(130, 130, 130, 0.5);
        }
    </style>

}
@section Admin{
    class="active"
}

<div id="overlay" style="display:none;text-align:center;">
    <img src="~/Content/img/spinner.gif" style="resize:inherit;" />
    <br />
</div>


<!-- Page Header-->
<header class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Manage - Departments</h2>
    </div>
</header>
<!-- Forms Section-->
<section class="forms">
    <div class="container-fluid" style="position:relative">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center">
                            <h3 class="h4">Department List</h3>
                            <!-- Button trigger modal -->
                            <button type="button" class="btn btn-primary ml-auto modalBtn" data-targetid="newDegree" data-role="Add">
                                Add New
                            </button>
                        </div>
                        <div class="card-body" style="overflow-y: scroll; max-height: 550px;">

                            <table class="table table-striped table-hover">
                                <tr>

                                    <th>
                                        @Html.DisplayNameFor(model => model.Departments.First().Name)
                                    </th>
                                    <th>Action</th>
                                </tr>

                                @foreach (var item in Model.Departments)
                                {
                                    <tr>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            <a href="#" class="modalBtn" data-targetid="@item.Id" data-role="Edit">Edit</a> |
                                            <a href="#" class="modalBtn" data-targetid="@item.Id" data-role="Delete">Delete</a>
                                        </td>
                                    </tr>
                                }

                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalBody">
                    ...
                </div>
                <div class="modal-footer" id="modalFooter">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" id="closeBtn" data-pagerefresh="false">Close</button>
                    <button type="button" class="btn btn-primary" id="saveChangesBtn">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script>
        $(document).ready(function () {

            $('#modal').on('hidden.bs.modal', function () {
                if ("true" == $("#closeBtn").data("pagerefresh")) location.reload();
            });

            $(".modalBtn").click(function () {
                $('#overlay').fadeIn();
                var id = $(this).data("targetid");
                var role = $(this).data("role");
                if ("" != role) {

                    $.ajax({
                        url: '@Url.Action("ManageForm", "MasterData")?mode=' + role + '&dataType=Department' + '&Id=' + id,
                        success: function (result) {
                            $("#modalBody").html(result);
                            $("#saveChangesBtn").show();
                        },
                        error: function () {
                            $('#modalBody').html('<div class="alert alert-danger" role="alert"> An Error has occured </div >');
                            $("#saveChangesBtn").hide();
                        },
                        fail: function (xhr, textStatus, errorThrown) {
                            $('#modalBody').html('<div class="alert alert-danger" role="alert">Request Failed with error: ' + errorThrown + '</div > ');
                            $("#saveChangesBtn").hide();
                        },
                        complete: function () {
                            $('#overlay').fadeOut();
                            $("#modalTitle").html(role +" Department");
                            $('#modal').modal('show');
                        }
                    });
                }
            });

            $("#saveChangesBtn").click(function () {
                $('#overlay').fadeIn();
                var formType = $('#manageForm').data('formtype');
                var formUrl = $('#manageForm').attr('action') + "?mode=" + formType;
                var formData = new FormData(document.getElementById('manageForm'));
                var text = null;
                switch (formType) {
                    case "Add": text = "added"; break;
                    case "Edit": text = "updated"; break;
                    case "Delete": text = "deleted"; break;
                }
                $.ajax({
                    url: formUrl,
                    type: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (result) {
                        if ('Success' == result) {
                            $('#modalBody').html('<div class="alert alert-success" role="alert"> Successfully ' + text + ' department</div >');
                            $("#saveChangesBtn").fadeOut();
                            $("#closeBtn").data("pagerefresh", "true")
                        } else {
                            $('#modalBody').html(result);
                            $("#saveChangesBtn").show();
                        }
                    },
                    error: function () {
                        $('#modalBody').html('<div class="alert alert-danger" role="alert"> An Error has occured </div >');
                        $("#saveChangesBtn").fadeOut();
                    },
                    fail: function (xhr, textStatus, errorThrown) {
                        $('#modalBody').html('<div class="alert alert-danger" role="alert">Request Failed with error: ' + errorThrown + '</div > ');
                        $("#saveChangesBtn").fadeOut();
                    },
                    complete: function () {
                        $('#overlay').fadeOut();
                    }
                });
            });

        });
    </script>
}

EmployeeInformationSystem.WebUI/Views/MasterData/Manage.cshtml
<html>
<body>
    <h1>Page under development for Datatype --- @ViewBag.Type</h1>
</body>
</html>