EmployeeInformationSystem.WebUI/Controllers/EmployeeDataController.cs
using EmployeeInformationSystem.Core.Contracts;
using EmployeeInformationSystem.Core.Models;
using EmployeeInformationSystem.Core.ViewModels;
using EmployeeInformationSystem.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeInformationSystem.WebUI.Controllers
{
    public class EmployeeDataController : BaseController
    {
        IRepository<EmployeeDetail> EmployeeDetailContext;
        IRepository<Discipline> DisciplineContext;
        IRepository<Designation> DesignationContext;
        IRepository<DependentDetail> DependentDetailContext;
        IRepository<Level> LevelContext;
        IRepository<Degree> DegreeContext;
        IRepository<HoD> HoDContext;
        IRepository<Organisation> OrganisationContext;
        IRepository<PastExperience> PastExperienceContext;
        IRepository<PayScale> PayScaleContext;
        IRepository<PostingDetail> PostingDetailContext;
        IRepository<PromotionDetail> PromotionDetailContext;
        IRepository<Department> DepartmentContext;
        IRepository<QualificationDetail> QualificationDetailContext;
        IRepository<TelephoneExtension> TelephoneExtensionContext;

        public EmployeeDataController(IRepository<EmployeeDetail> employeeDetailContext,
        IRepository<Discipline> disciplineContext,
        IRepository<DependentDetail> dependentDetailContext,
        IRepository<Level> levelContext,
        IRepository<Degree> degreeContext,
        IRepository<Designation> designationContext,
        IRepository<HoD> hoDContext,
        IRepository<Organisation> organisationContext,
        IRepository<PastExperience> pastExperienceContext,
        IRepository<PayScale> payScaleContext,
        IRepository<PostingDetail> postingDetailContext,
        IRepository<PromotionDetail> promotionDetailContext,
        IRepository<Department> departmentContext,
        IRepository<QualificationDetail> qualificationDetailContext,
        IRepository<TelephoneExtension> telephoneExtensionContext)
        {
            EmployeeDetailContext = employeeDetailContext;
            DisciplineContext = disciplineContext;
            LevelContext = levelContext;
            DegreeContext = degreeContext;
            DependentDetailContext = dependentDetailContext;
            DesignationContext = designationContext;
            HoDContext = hoDContext;
            OrganisationContext = organisationContext;
            PastExperienceContext = pastExperienceContext;
            PostingDetailContext = postingDetailContext;
            PayScaleContext = payScaleContext;
            PromotionDetailContext = promotionDetailContext;
            DepartmentContext = departmentContext;
            QualificationDetailContext = qualificationDetailContext;
            TelephoneExtensionContext = telephoneExtensionContext;

            //Setting Parameters for Page
            base.SetGlobalParameters();
            ViewBag.UserName = UserName;
            ViewBag.ProfilePhoto = ProfilePicture;
            ViewBag.Role = Role;
        }

        [Authorize(Roles= "Add")]
        public ActionResult AddEmployee()
        {
            return View();
        }

        [Authorize(Roles = "Add,Edit")]
        public ActionResult AjaxAdd(string targetPage, string mode, string EmployeeId)
        {
            // Empty ViewModel & Select List
            DataViewModel viewModel = null;
            List<SelectListItem> employeeType = new List<SelectListItem>() { new SelectListItem() { Text = "--Select Employee Type--", Value = "" } };
            string organisationName = "DGH";
            //If Method called for editing, Check if Emp ID passed along with it
            if (mode == "Edit" & null != EmployeeId)
            {
                EmployeeDetail employee = EmployeeDetailContext.Find(EmployeeId); //Fetch Employee from DB
                if (null != employee)
                {
                    viewModel = new DataViewModel() // Create View Model based on the Employee & its related fields
                    {
                        EmployeeDetails = employee,
                        DependentDetails = DependentDetailContext.Collection().Where(d => d.EmployeeId == employee.Id).ToList(),
                        TelephoneExtensions = TelephoneExtensionContext.Collection().FirstOrDefault(t => t.EmployeeId == employee.Id),
                        QualificationDetails = QualificationDetailContext.Collection().Where(q => q.EmployeeId == employee.Id).ToList(),
                        PastExperiences = PastExperienceContext.Collection().Where(p => p.EmployeeId == employee.Id).ToList(),
                        PromotionDetails = PromotionDetailContext.Collection().Where(p => p.EmployeeId == employee.Id).ToList(),
                        PostingDetails = PostingDetailContext.Collection().Where(p => p.EmployeeId == employee.Id).ToList()
                    };
                    if (null != employee.AadhaarNumber)
                    {
                        viewModel.AadhaarPart1 = employee.AadhaarNumber.Substring(0, 4);
                        viewModel.AadhaarPart2 = employee.AadhaarNumber.Substring(4, 4);
                        viewModel.AadhaarPart3 = employee.AadhaarNumber.Substring(8, 4);
                    }
                    // BUG FIX: For Consultants/Advisors others Empty promotion details causes page rendering to fail, initialize empty promotion detail List to be filled during EDIT
                    if (0 == viewModel.PromotionDetails.Count && EmployeeType.Deputationist != employee.EmployeeType) viewModel.PromotionDetails.Add(new PromotionDetail());
                    organisationName = null != employee.Organisation ? employee.Organisation.Name : "DGH"; // Temp Bug fix to resolve issue with empty Org Names
                }
                else
                {
                    return HttpNotFound(); // Employee not in DB
                }

            }
            else // If passed for Addition
            {
                viewModel = new DataViewModel() // Create empty view model with basic common parameters of new Employee
                {
                    EmployeeDetails = new EmployeeDetail()
                    {
                        MaritalStatus = MaritalStatus.Single,
                        WorkingStatus = true
                    }
                };
            }
            switch (targetPage)
            {
                case "Deputationist":
                    employeeType.Add(new SelectListItem() { Text = "Deputationist", Value = "0" }); // Add fields to drop down accordingly
                    break;
                case "Consultant":
                    employeeType.Add(new SelectListItem() { Text = "Adviser", Value = "1" });
                    employeeType.Add(new SelectListItem() { Text = "Consultant", Value = "2" });
                    break;
                case "Contractual":
                    employeeType.Add(new SelectListItem() { Text = "Contractual - DGH Staff", Value = "3" });
                    employeeType.Add(new SelectListItem() { Text = "Contractual - MoPNG Staff", Value = "4" });
                    employeeType.Add(new SelectListItem() { Text = "Trainee Officer", Value = "5" });
                    employeeType.Add(new SelectListItem() { Text = "Others", Value = "6" });
                    break;
                default: break;
            }
            viewModel.EmployeeType = employeeType; // Add appropiate employeeType dropdown to ViewModel
            viewModel.Degrees = DegreeContext.Collection().OrderBy(d => d.Name); // Master Data for Degrees dropdown
            viewModel.Disciplines = DisciplineContext.Collection().OrderBy(d => d.Name); // Master Data for Disciplines dropdown
            /*
             * Designations, Levels, PayScales are filtered to contain only DGH Specific data.
             * The fields for other organisations are handled via separate AJAX-JSON Method
             */
            viewModel.Designations = DesignationContext.Collection().Where(d => d.Organisation.Name == organisationName).OrderBy(d => d.Name); //DGH Specific OR Org specific if for Editing
            viewModel.Levels = LevelContext.Collection().Where(l => l.Organisation.Name == organisationName).OrderBy(l => l.Name); //DGH Specific OR Org specific if for Editing
            viewModel.PayScales = PayScaleContext.Collection().Where(p => p.Organisation.Name == organisationName).OrderBy(p => p.Scale); //DGH Specific OR Org specific if for Editing
            viewModel.Organisations = OrganisationContext.Collection().Where(o => o.Name != "DGH").OrderBy(o => o.Name); // All organisations except DGH must be in dropdown
            viewModel.Departments = DepartmentContext.Collection().OrderBy(d => d.Name); // Master Data for Departments dropdown
            viewModel.HoDs = HoDContext.Collection().OrderBy(d => d.Designation); //Add proper support for determining current HoDs based on date
            ViewBag.Mode = mode;
            return View(targetPage, viewModel);
        }

        [Authorize(Roles = "Add")]
        [HttpPost]
        public ActionResult AjaxAdd(DataViewModel viewModel, HttpPostedFileBase file)
        {
            ViewBag.Mode = "Add";
            string returnText = "Error";
            string EmpId = null;

            /*
            CHECK FOR UNIQUE EMPLOYEE-CODE
            */
            EmpId = (from employee in EmployeeDetailContext.Collection()
                     where employee.EmployeeCode == viewModel.EmployeeDetails.EmployeeCode
                     select employee.Id).FirstOrDefault();
            if (null != EmpId)
            {
                ModelState.AddModelError("", "An Employee with identical Employee Code/CPF already exists! Please select another value");
            }
            if (!ModelState.IsValid)
            {

EmployeeInformationSystem.WebUI/Views/EmployeeData/Add.cshtml
@{
    ViewBag.Title = "Add Employee";
}

@section CustomStyles{
    @Styles.Render("~/Content/gijgo")
    <style>
        #overlay {
            position: absolute;
            justify-content: left;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba(130, 130, 130, 0.5);
        }
    </style>

}
@section DataManage{
    show
}
@section AddEmployee{
    class="active"
}


@model EmployeeInformationSystem.Core.ViewModels.DataViewModel
<div id="overlay" style="display:none;text-align:center;">
    <img src="~/Content/img/spinner.gif" style="resize:inherit;" />
    <br />
</div>
<!-- Page Header-->
<header class="page-header">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Add Employee Data</h2>
    </div>
</header>
<!-- Forms Section-->
<section class="forms">
    <div class="container-fluid" style="position:relative">

        <div class="row">
            <div class="col-lg-12">
                <div class="card" id="AddDataForm">
                    <div class="card-header d-flex align-items-center">
                        <h3 class="h4">Select Type</h3>
                    </div>

                    <div class="card-body mx-auto">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="account" class="mr-5 form-control" style="width:500px" id="chooseEmployeeType">
                                    <option value="NA" selected="selected">--Select option--</option>
                                    <option value="Deputationist">Deputationist</option>
                                    <option value="Consultant">Advisor/Consultant</option>
                                    <option value="Contractual">Contractual</option>
                                </select>
                            </div>
                            <div class="form-group ">
                                <button type="submit" class="ml-5 form-control btn btn-primary" id="continueBtn" disabled>Continue</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@section Scripts{
    @Scripts.Render("~/bundles/gijgo")
    <script>
        $(document).ready(function () {
            $("#chooseEmployeeType").change(function () {
                var selectedOption = $(this).children("option:selected").val();
                if ("NA" == selectedOption && !$("#continueBtn").prop('disabled')) {
                    $('#continueBtn').attr('disabled', true);
                } else {
                    $('#continueBtn').removeAttr('disabled');
                }
            });
            $('#continueBtn').click(function () {
                $('#overlay').fadeIn();
                var targetPage = $("#chooseEmployeeType").children("option:selected").val();
                if ('NA' != targetPage) {
                    $.ajax({
                        url: '@Url.Action("AjaxAdd", "EmployeeData")?targetPage=' + targetPage,
                        success: function (result) {
                            $('#AddDataForm').html(result);
                        },
                        error: function () {
                            $('#AddDataForm').html('<div class="alert alert-danger" role="alert"> An Error has occured </div >');
                        },
                        fail: function (xhr, textStatus, errorThrown) {
                            $('#AddDataForm').html('<div class="alert alert-danger" role="alert">Request Failed with error: ' + errorThrown + '</div > ');
                        }
                    });
                }
                //$('#overlay').fadeOut();
            });
        });
    </script>
}

EmployeeInformationSystem.WebUI/Views/EmployeeData/AddEmployee.cshtml
@{
    ViewBag.Title = "Add Employee";
}

@section CustomStyles{
    @Styles.Render("~/Content/gijgo")
    <style>
        #overlay {
            position: absolute;
            justify-content: left;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba(130, 130, 130, 0.5);
        }
    </style>

}
@section DataManage{
    show
}
@section AddEmployee{
    class="active"
}

<div id="overlay" style="display:none;text-align:center;">
    <img src="~/Content/img/spinner.gif" style="resize:inherit;" />
    <br />
</div>
<!-- Page Header-->
<header class="page-header bg-success text-white">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">Add Employee Data</h2>
    </div>
</header>
<!-- Forms Section-->
<section class="forms">
    <div class="container-fluid" style="position:relative">

        <div class="row">
            <div class="col-lg-12">
                <div class="card" id="AddDataForm">
                    <div class="card-header d-flex align-items-center">
                        <h3 class="h4">Select Type</h3>
                    </div>

                    <div class="card-body mx-auto">
                        <div class="form-inline">
                            <div class="form-group">
                                <select name="account" class="mr-5 form-control" style="width:500px" id="chooseEmployeeType">
                                    <option value="NA" selected="selected">--Select option--</option>
                                    <option value="Deputationist">Deputationist</option>
                                    <option value="Consultant">Advisor/Consultant</option>
                                    <option value="Contractual">Contractual</option>
                                </select>
                            </div>
                            <div class="form-group ">
                                <button type="submit" class="ml-5 form-control btn btn-primary" id="continueBtn" disabled>Continue</button>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@section Scripts{
    @Scripts.Render("~/bundles/gijgo")
    <script>
        $(document).ready(function () {
            $("#chooseEmployeeType").change(function () {
                var selectedOption = $(this).children("option:selected").val();
                if ("NA" == selectedOption && !$("#continueBtn").prop('disabled')) {
                    $('#continueBtn').attr('disabled', true);
                } else {
                    $('#continueBtn').removeAttr('disabled');
                }
            });
            $('#continueBtn').click(function () {
                $('#overlay').fadeIn();
                var targetPage = $("#chooseEmployeeType").children("option:selected").val();
                if ('NA' != targetPage) {
                    $.ajax({
                        url: '@Url.Action("AjaxAdd", "EmployeeData")?targetPage=' + targetPage +'&mode=Add',
                        success: function (result) {
                            $('#AddDataForm').html(result);
                        },
                        error: function () {
                            $('#AddDataForm').html('<div class="alert alert-danger" role="alert"> An Error has occured </div >');
                        },
                        fail: function (xhr, textStatus, errorThrown) {
                            $('#AddDataForm').html('<div class="alert alert-danger" role="alert">Request Failed with error: ' + errorThrown + '</div > ');
                        }
                    });
                }
                //$('#overlay').fadeOut();
            });
        });
    </script>
}

EmployeeInformationSystem.WebUI/Views/EmployeeData/SelectEmployee.cshtml
@model EmployeeInformationSystem.Core.Models.EmployeeDetail

@section CustomStyles{
    @Styles.Render("~/Content/bootstrap-select")
    @Styles.Render("~/Content/gijgo")
    <style>
        #overlay {
            position: absolute;
            justify-content: left;
            z-index: 1000;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: rgba(130, 130, 130, 0.5);
        }
    </style>
}
@section DataManage{
    show
}
@{ string headerClass = "";}
@switch (ViewBag.Target)
{
    case "View":headerClass = "bg-info";
        @section ViewEmployee{
            class="active"
    } break;
    case "Edit":headerClass = "bg-warning";
        @section EditEmployee{
        class="active"
    } break;
    case "Delete": headerClass = "bg-danger";
        @section DeleteEmployee{
    class="active"
    } break;
}

<div id="overlay" style="display:none;text-align:center;">
    <img src="~/Content/img/spinner.gif" style="resize:inherit;" />
    <br />
</div>

<!-- Page Header-->

<header class="page-header @headerClass text-white">
    <div class="container-fluid">
        <h2 class="no-margin-bottom">@ViewBag.Target Employee Data</h2>
    </div>
</header>
<!-- Forms Section-->
<section class="forms">
    <div class="container-fluid" style="position:relative">

        <div class="row">
            <div class="col-lg-12">
                <div class="card" id="AddDataForm">
                    <div class="card-header d-flex align-items-center">
                        <h3 class="h4">Select Employee</h3>
                    </div>

                    <div class="card-body ml-4">
                        <div class="form-inline">
                            <div class="form-group col-4">
                                <input id="radioNameSearch" type="radio" value="name" name="radioEmployeeOption" class="radio-template">
                                <label for="radioNameSearch">Search using Name</label>
                            </div>
                            <div class="form-group col-8">
                                <select name="selectEmployeeOption" class="form-control selectEmployeeOption" id="selectEmployeeByName" style="min-width:80%;" data-live-search="true">
                                    <option value="" selected>--Select Employee Name--</option>
                                    @foreach (var employee in ViewBag.Employees)
                                    {
                                        <option value="@employee.Id" data-employeetype="@employee.EmployeeType">@employee.GetFullName</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <br /><br />
                        <div class="form-inline">
                            <div class="form-group col-4">
                                <input id="radioCodeSearch" type="radio" value="code" name="radioEmployeeOption" class="radio-template">
                                <label for="radioCodeSearch">Search using Employee Code/CPF</label>
                            </div>
                            <div class="form-group col-8">
                                <select name="selectEmployeeOption" class="form-control selectEmployeeOption" id="selectEmployeeByCode" style="min-width:80%;" data-live-search="true">
                                    <option value="" selected>--Select Employee Code--</option>
                                    @foreach (var employee in ViewBag.Employees)
                                    {
                                        <option value="@employee.Id" data-employeetype="@employee.EmployeeType">@employee.EmployeeCode</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <br /><br />
                        <div class="form-inline">
                            <div class="form-group col-4">
                                <input id="radioMobileSearch" type="radio" value="mobile" name="radioEmployeeOption" class="radio-template">
                                <label for="radioMobileSearch">Search using Mobile Number</label>
                            </div>
                            <div class="form-group col-8">
                                <select name="selectEmployeeOption" class="form-control selectEmployeeOption" id="selectEmployeeByMobile" style="min-width:80%;" data-live-search="true">
                                    <option value="" selected>--Select Employee Mobile Number--</option>
                                    @foreach (var employee in ViewBag.Employees)
                                    {
                                        if (null != employee.MobileNumber)
                                        {
                                            <option value="@employee.Id" data-employeetype="@employee.EmployeeType">@employee.MobileNumber</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <br /><br />
                        <div class="form-group col-4 ">
                            <button type="submit" class="form-control btn btn-primary" id="continueBtn" disabled>Continue</button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
@section Scripts{
    @Scripts.Render("~/bundles/bootstrap-select")
    @Scripts.Render("~/bundles/gijgo")
    <script>
        $(document).ready(function () {
            $('select').prop('disabled', true).selectpicker({
            liveSearchStyle: "contains"
            });

            $('input[type="radio"][name="radioEmployeeOption"').change(function () {
                $('select').prop('disabled', true).val("");
                $('#continueBtn').prop('disabled', true);
                switch (this.value) {
                    case "name":
                        $("#selectEmployeeByName").prop('disabled', false);
                        break;
                    case "code":
                        $("#selectEmployeeByCode").prop('disabled', false);
                        break;
                    case "mobile":
                        $("#selectEmployeeByMobile").prop('disabled', false);
                        break;
                }
                $('select').selectpicker('refresh');
            });


            $(document).on('propertychange change click keyup input paste', 'select', function () {
                if (this.value != "") {
                    $('#continueBtn').prop('disabled', false);
                } else {
                    $('#continueBtn').prop('disabled', true);
                }
            });

            $('#continueBtn').click(function () {
                var EmployeeId = null;
                EmployeeId = $("select:enabled").val();
                if ("" != EmployeeId) {
                    @if("View" == ViewBag.Target || "Delete" == ViewBag.Target)
                    {
                    <text>
                    window.location.href = '@Url.Action("View" == ViewBag.Target ?"ViewEmployee": "DeleteEmployee", "EmployeeData")?EmployeeId=' + EmployeeId;
                    </text>
                    }
                    else
                    {
                    <text>
                    $('#overlay').fadeIn();
                        var employeeType = $("select:enabled").find(':selected').data('employeetype');
                        var targetPage = "Contractual";
                        if (employeeType == "Deputationist") {
                            targetPage = "Deputationist";
                        } else if (employeeType == "Advisor" || employeeType == "Consultant") {
                            targetPage = "Consultant";
                        }
                        if ('NA' != targetPage) {
                        $.ajax({
                            url: '@Url.Action("AjaxAdd", "EmployeeData")?targetPage=' + targetPage + '&mode=Edit&EmployeeId=' + EmployeeId,
                            success: function (result) {
                                $('#AddDataForm').html(result);
                                },
                            error: function () {
                                $('#AddDataForm').html('<div class="alert alert-danger" role="alert"> An Error has occured </div >');
                                },
                            fail: function (xhr, textStatus, errorThrown) {
                                $('#AddDataForm').html('<div class="alert alert-danger" role="alert">Request Failed with error: ' + errorThrown + '</div > ');
                                }
                            });
                        }
                    </text>
                    }
                } else {
                    alert("No Employee Selected !!");
                }

            });
        });
    </script>
}

EmployeeInformationSystem.WebUI/Views/EmployeeData/Success.cshtml
@{
    Layout = null;
}
@if (null != ViewBag.Mode)
{
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Success!</h4>
        <p>Successfully @(ViewBag.Mode == "Add"? "Added": "Edited") user with Employee Code/CPF No. @ViewBag.EmployeeCode</p>
        <hr>
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <button type="button" onclick="window.location.href = '@Url.Action("ViewEmployee", "EmployeeData", new { EmployeeId = ViewBag.EmployeeId })';" class="btn btn-primary">View @(ViewBag.Mode == "Add" ? "Added" : "Edited") Employee</button>
                    <button type="button" class="btn btn-secondary" onclick="window.location.href = '@Url.Action(ViewBag.Mode == "Add"? "AddEmployee":"EditEmployee", "EmployeeData")';">@(ViewBag.Mode == "Add" ? "Add" : "Edit") another Employee</button>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="alert alert-danger" role="alert"> An Error has occured </div>
}